### ISSUE TITLE
./configure crashes.

### ISSUE THREAD

**Issue by defleury** [jfmrod/hpc-clust#3]
The following line in the configure scripts leads to a crash due to a syntax error in subsequent lines:

```
AX_PTHREAD()
```

(line 3408 in configure after ./bootstrap-ping on my system)

After commenting that line out, ./configure works fine, but I get a crash upon compilation (see separate issue).

**Comment by jfmrod** [comment]
can you check if you have the most up to date version, the bootstrap script should look like:
#!/bin/bash

autoreconf -vfi -I m4
#aclocal -I m4 && autoconf && autoheader && automake -a
pushd eutils
./bootstrap
popd

The other error occurs due to the configure script not configuring correctly a header file, it seems that the configure script didnt finish running or was not generated correctly

**Comment by defleury** [comment]
Solved by uncommenting the following line from the bootstrap script:

```
#aclocal -I m4 && autoconf && autoheader && automake -a
```

The issue seems to have been old versions in context of our CentOS 6.5.

Thanks again, J!

:-)
